import { Kirang_Haerang } from "next/font/google";
import Header from "../components/Header"
import "./globals.css";

const kirangHaerang = Kirang_Haerang({
  variable: "--font-kirang-haerang",
  weight: '400', 
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kirangHaerang.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
